### PR TITLE
fix(log): Activity log

### LINKED ISSUE #32: Bottom bar is scrolling around with new layout when viewing Activity Log
The activity log has a layout bug:
If you're scrolling through a readonably long log then it won't be visible intially.
If you then however scroll down it will somehow appear as if it was a mis-aligned part ot the log.:

grafik

### PR DESCRIPTION
**Pull request by tom-schoener**
Closes #32
This PR removes the infinite scroll dependency.

### CODE REVIEW

**Comment by philmtd** [comment]
Closes #32

**Comment by tom-schoener** [comment]
This PR primarily fixes ws and activity log bugs. For activity log improvements a new PR should be created. This is ready for review.

File: frontend/src/app/activity/activity-log/activity-log.component.ts [hunk 1]
```diff
@@ -26,117 +24,71 @@ const activityIconMap = {
...
-  }
-
-  public loadMore() {
-    if (this.infiniteScrollDisabled) {
-      return;
+  public paginationEvent(page: PageEvent) {
+    this.loadPage(page);
+    if (page.pageIndex === 0) {
+      this.pendingActivities = [];
     }
```
Comment (philmtd) [inline frontend/src/app/activity/activity-log/activity-log.component.ts:72]: The page size is not saved in `this.pageSettings.pageSize`. If you use a different page size than the default, e.g. 100, and hit the refresh button, it will only reload 10 items.

File: frontend/src/app/rest/page.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+  empty: boolean
+}
+
+export interface Pageable {
+  sort: PageSort
+  offset: number
+  pageNumber: number
+  pageSize: number
+  paged: boolean
+  unpaged: boolean
```
Comment (philmtd) [inline frontend/src/app/rest/page.ts:14]: I'd remove this if it isn't necessary.

File: frontend/src/app/rest/page.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+}
+
+export interface Page<T> {
+  content: Array<T>
+  empty: boolean
```
Comment (philmtd) [inline frontend/src/app/rest/page.ts:19]: Can't this be calculated by checking if `content` is empty? Having this as a separate property may, theoretically, lead to this being true/false while the other is not empty/empty.

File: src/main/java/io/oneko/websocket/SessionWebSocketHandler.java [hunk 4]
```diff
@@ -94,11 +99,11 @@ public void send(String sessionId, ONekoWebSocketMessage message) {
 	}
 
 	public void broadcast(ONekoWebSocketMessage message) {
-		for (WebSocketSessionContext ctx : new ArrayList<>(sessionContextMap.values())) {
+		for (WebSocketSessionContext ctx : sessionContextMap.values()) {
 			WebSocketSession session = ctx.getSession();
 			if (!session.isOpen()) {
-				log.debug("Ws session with id {} is already closed, we skip this one.", ctx.getId());
-				invalidateSession(ctx.getId());
+				log.debug("Ws session with id {} is already closed, we skip this one.", ctx.getWsSessionId());
```
Comment (philmtd) [inline src/main/java/io/oneko/websocket/SessionWebSocketHandler.java:105]: This could also be logged as trace.

File: src/main/java/io/oneko/websocket/WebSocketSessionContext.java [hunk 5]
```diff
@@ -38,12 +41,13 @@ public static WebSocketSessionContext of(WebSocketSession wsSession) {
...
 				.session(wsSession)
-				.id(sessionId)
+				.wsSessionId(wsSession.getId())
+				.userSessionId(sessionCookieId)
 				.build();
 	}
 
 	public void close() {
-		log.debug("Closing WebSocket session {}", id);
+		log.debug("Closing WebSocket session {}", wsSessionId);
```
Comment (philmtd) [inline src/main/java/io/oneko/websocket/WebSocketSessionContext.java:50]: This could also be logged as trace.

**Review by philmtd — CHANGES_REQUESTED** [review]

File: frontend/src/app/rest/page.ts (hunk 3 above)
Comment (tom-schoener) [reply frontend/src/app/rest/page.ts:19]: This interface mirrors Spring's `Page` interface.

**Review by philmtd — APPROVED** [review]
