### PR TITLE
fix: Running DockerRegistryPolling jobs should not get stuck

### LINKED ISSUE #5: DockerRegistryPolling should not get stuck
I've observed that the DockerRegistryPolling might get stuck in a state where a job appears to be running even though it isn't. This should not be possible.

### PR DESCRIPTION
**Pull request by philmtd**
The jobs will not time out after five minutes and should generally be more stable.

This addresses and closes #5.

### CODE REVIEW

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java [hunk 1]
```diff
@@ -67,23 +72,41 @@
 	@Scheduled(fixedDelay = 20000, initialDelay = 20000)
 	protected void checkDockerForNewImages() {
 		if (!this.pollingInProgress.getAndSet(true)) {
+			log.trace("Starting polling job");
```
Comment (schwerlaut) [inline src/main/java/io/oneko/docker/DockerRegistryPolling.java]: I think that if a log writes "Starting XYZ" then it should write "Finished XYZ" as well.
To keep things clear both log-statements should be written by the same method or at least twin-methods.

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java [hunk 2]
```diff
@@ -55,6 +57,9 @@
 	private final AtomicBoolean pollingInProgress = new AtomicBoolean(false);
 	private final ExpiringBucket<UUID> failedManifestRequests = new ExpiringBucket<UUID>(Duration.ofMinutes(5)).concurrent();
 
+	private Instant lastPollingJobStartDate = null;
```
Comment (schwerlaut) [inline src/main/java/io/oneko/docker/DockerRegistryPolling.java]: Since this is reset always, it should be namend currentPollingJobStartDate.
I even think, that It might be helpful to gather date and disposable into a DockerRegistryPollingJob (or something like that) class, that support control methods like shouldCancel() cancel etc.

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java [hunk 3]
```diff
@@ -67,23 +72,41 @@
...
 					collectList();
 			final Mono<List<Project>> projectsMono = projectRepository.getAll()
 					.collectList();
-			meshesMono.zipWith(projectsMono)
-					.subscribe(pair -> this.checkDockerForNewImages(pair.getT1(), pair.getT2()));
+			this.currentPollingJob = meshesMono.zipWith(projectsMono)
+					.flatMap(pair -> this.checkDockerForNewImages(pair.getT1(), pair.getT2()))
+					.subscribe();
+		} else if (shouldPollingJobBeTimedOut() || this.currentPollingJob.isDisposed()) {
+			log.info("Timing out polling job.");
```
Comment (schwerlaut) [inline src/main/java/io/oneko/docker/DockerRegistryPolling.java]: The job actually yet timed out so we cancel it here.

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java [hunk 4]
```diff
@@ -67,23 +72,41 @@
...
+			this.currentPollingJob.dispose();
+			this.currentPollingJob = null;
+			setPollingJobToNotRunning();
 		} else {
 			log.debug("Skipping job because another polling job is still running.");
 		}
 	}
 
+	private boolean shouldPollingJobBeTimedOut() {
+		final Duration pollingTimeout = Duration.ofMinutes(5);
```
Comment (schwerlaut) [inline src/main/java/io/oneko/docker/DockerRegistryPolling.java]: 5 Minutes seems quite arbitrary.

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java (hunk 2 above)
Comment (schwerlaut) [reply src/main/java/io/oneko/docker/DockerRegistryPolling.java]: And such a class might be all covered in unit tests. Wouldn't that be fun?

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java (hunk 4 above)
Comment (philmtd) [reply src/main/java/io/oneko/docker/DockerRegistryPolling.java]: Because it is. I can make it less static though.

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java (hunk 1 above)
Comment (philmtd) [reply src/main/java/io/oneko/docker/DockerRegistryPolling.java]: Fixed this.

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java (hunk 2 above)
Comment (philmtd) [reply src/main/java/io/oneko/docker/DockerRegistryPolling.java]: > Wouldn't that be fun?

Indeed!

**Comment by philmtd** [comment]
I've addressed the issues, could you re-review it?

File: src/main/java/io/oneko/docker/DockerRegistryPolling.java (hunk 3 above)
Comment (philmtd) [reply src/main/java/io/oneko/docker/DockerRegistryPolling.java]: Fixed
